use ps_hkey::{DOUBLE_HASH_SIZE_COMPACT, MAX_DECRYPTED_SIZE};
use ps_uuid::UUID_BYTES;

pub const LEAF_HEIGHT: u8 = 0;
pub const MAX_CHILDREN: usize = MAX_DECRYPTED_SIZE / (UUID_BYTES + 1 + DOUBLE_HASH_SIZE_COMPACT);
